#!/usr/bin/env python3
"""Render every field-level description in the deposit from the one dictionary.

FIELDS.json is authoritative. This script is the only writer of:

  * FIELDS.md                       - human-readable dictionary
  * README.md section 2             - between the GENERATED markers
  * croissant.json field dataType   - typed from the Parquet schema, never from
    and field description             observed values
  * a Data Records table for the paper (--data-records, written outside the
    deposit)

so README, croissant and the paper cannot drift apart. Nothing here touches
croissant's `distribution` block, MANIFEST.sha256 or MANIFEST.json: file hashes
are regenerated by the manifest tooling, after this script has run.

Usage:
    python3 build_field_docs.py --deposit /path/to/deposit_v3 \
        [--data-records /workspace/reports/data_records_table.md] [--check]

--check validates and reports without writing.
"""
import argparse
import json
import os
import sys

# Parquet physical/logical type -> croissant dataType. The mapping is total over
# the types this deposit uses; an unmapped type is an error rather than a
# silent sc:Text fallback (that fallback is what produced the original drift).
CROISSANT_TYPE = {
    "string": "sc:Text",
    "int16": "sc:Integer",
    "int32": "sc:Integer",
    "int64": "sc:Integer",
    "float": "sc:Float",
    "double": "sc:Float",
    "bool": "sc:Boolean",
}

BEGIN = "<!-- BEGIN GENERATED FROM FIELDS.json - do not edit by hand -->"
END = "<!-- END GENERATED FROM FIELDS.json -->"


def load_dictionary(deposit):
    with open(os.path.join(deposit, "FIELDS.json")) as fh:
        d = json.load(fh)
    for f in d["fields"]:
        want = CROISSANT_TYPE.get(f["parquet_type"])
        if want is None:
            raise SystemExit(f"unmapped parquet_type {f['parquet_type']!r} on {f['name']}")
        if f.get("croissant_type") != want:
            raise SystemExit(
                f"{f['record_set']}.{f['name']}: croissant_type {f.get('croissant_type')!r} "
                f"disagrees with parquet_type {f['parquet_type']!r} (expected {want})"
            )
    return d


def by_record_set(d):
    out = {}
    for f in d["fields"]:
        out.setdefault(f["record_set"], {})[f["name"]] = f
    return out


def record_set_of(rs_id):
    """Croissant recordSet @id -> dictionary record set name."""
    if rs_id.endswith("_meta"):
        return "meta"
    if rs_id.endswith("_contacts"):
        return "contacts"
    if rs_id == "residues_corpus":
        return "residues_corpus"
    raise SystemExit(f"cannot classify recordSet {rs_id!r}")


def croissant_description(f):
    """One flat string: definition, unit, population, then each caveat."""
    parts = [f["definition"].rstrip(".") + "."]
    if f.get("unit"):
        parts.append(f"Unit: {f['unit']}.")
    parts.append(f"Populated in: {f['populated_in']}.")
    if f.get("null_when") and f["null_when"] != "never":
        parts.append(f"Null when: {f['null_when']}.")
    parts.extend(c.rstrip(".") + "." for c in f.get("caveats", []))
    return " ".join(parts)


# ---------------------------------------------------------------- verification

def verify_against_parquet(deposit, index):
    """Every Parquet column must have a dictionary entry of the same type."""
    try:
        import pyarrow.parquet as pq
    except ImportError:
        print("pyarrow unavailable - skipping Parquet cross-check", file=sys.stderr)
        return []
    problems = []
    labels = os.path.join(deposit, "labels")
    files = []
    if os.path.isdir(labels):
        files += [(os.path.join(labels, n), "meta" if n.endswith("_meta.parquet") else "contacts")
                  for n in sorted(os.listdir(labels)) if n.endswith(".parquet")]
    res = os.path.join(deposit, "metadata", "residues_corpus.parquet")
    if os.path.exists(res):
        files.append((res, "residues_corpus"))
    for path, rs in files:
        schema = pq.ParquetFile(path).schema_arrow
        for name, typ in zip(schema.names, [str(t) for t in schema.types]):
            entry = index.get(rs, {}).get(name)
            if entry is None:
                problems.append(f"{os.path.basename(path)}: column {name!r} has no FIELDS.json entry")
            elif entry["parquet_type"] != typ:
                problems.append(
                    f"{os.path.basename(path)}: column {name!r} is {typ} on disk, "
                    f"FIELDS.json says {entry['parquet_type']}"
                )
    return problems


# ------------------------------------------------------------------- renderers

def render_fields_md(d, index):
    L = [
        "# Field dictionary",
        "",
        "Authoritative definition of every column in this deposit. Generated from",
        "`FIELDS.json`; `README.md` section 2 and the `croissant.json` field descriptions",
        "are generated from the same file, so the three cannot disagree. To change a",
        "definition, edit `FIELDS.json` and re-run `build_field_docs.py`.",
        "",
        "Types are taken from the Parquet schema, not from observed values: a column that",
        "is entirely null in one file still carries its real type there.",
        "",
    ]
    for rs, spec in d["record_sets"].items():
        L += [f"## Record set `{rs}` - {spec['title']}", ""]
        L += [f"Files: `{spec['files']}`  ", f"Grain: {spec['grain']}", ""]
        if spec.get("note"):
            L += [spec["note"], ""]
        L += ["| field | type | unit | populated in |", "|---|---|---|---|"]
        for f in d["fields"]:
            if f["record_set"] != rs:
                continue
            L.append(f"| `{f['name']}` | {f['parquet_type']} | {f.get('unit') or '-'} | {f['populated_in']} |")
        L.append("")
        for f in d["fields"]:
            if f["record_set"] != rs:
                continue
            L += [f"### `{f['name']}`", ""]
            L += [f"**Type** `{f['parquet_type']}` (croissant `{f['croissant_type']}`)"
                  + (f" &nbsp; **Unit** {f['unit']}" if f.get("unit") else ""), ""]
            L += [f["definition"], ""]
            L += [f"*Populated in:* {f['populated_in']}.", ""]
            if f.get("null_when") and f["null_when"] != "never":
                L += [f"*Null when:* {f['null_when']}.", ""]
            if f.get("caveats"):
                for c in f["caveats"]:
                    L.append(f"- {c}")
                L.append("")
    return "\n".join(L).rstrip() + "\n"


def render_readme_section(d):
    """The block README section 2 carries between the GENERATED markers."""
    L = []
    for rs, spec in d["record_sets"].items():
        L.append(f"{rs} ({spec['grain']}):")
        for f in d["fields"]:
            if f["record_set"] != rs:
                continue
            unit = f" [{f['unit']}]" if f.get("unit") else ""
            L.append(f"  {f['name']:<15s} {f['parquet_type']:<7s}{unit}")
            L.append(f"      {f['definition']}")
            if f["populated_in"] != "all files" and not f["populated_in"].startswith("all 9"):
                L.append(f"      populated in: {f['populated_in']}")
            for c in f.get("caveats", []):
                L.append(f"      ! {c}")
        L.append("")
    L.append("Full definitions, including every null convention: FIELDS.md (generated")
    L.append("from FIELDS.json, which is the authoritative source for this section).")
    return "\n".join(L)


def render_data_records(d):
    """Paper-ready Data Records table, same source as everything else."""
    L = ["# Data Records - generated from deposit_v3/FIELDS.json", "",
         "Paste into the Data Records section. Regenerate rather than editing.", ""]
    for rs, spec in d["record_sets"].items():
        L += [f"**{spec['title']}** (`{spec['files']}`). {spec['grain'][0].upper()}{spec['grain'][1:]}.", ""]
        L += ["| Field | Type | Unit | Description |", "|---|---|---|---|"]
        for f in d["fields"]:
            if f["record_set"] != rs:
                continue
            desc = f["definition"]
            if f["populated_in"] not in ("all files",) and not f["populated_in"].startswith("all 9"):
                desc += f" Populated in {f['populated_in']}."
            L.append(f"| `{f['name']}` | {f['parquet_type']} | {f.get('unit') or '-'} | {desc} |")
        L.append("")
    return "\n".join(L)


# --------------------------------------------------------------------- writers

def patch_croissant(deposit, index, write):
    path = os.path.join(deposit, "croissant.json")
    with open(path) as fh:
        cr = json.load(fh)
    retyped = described = 0
    for rset in cr["recordSet"]:
        rs = record_set_of(rset["@id"])
        for field in rset["field"]:
            entry = index[rs].get(field["name"])
            if entry is None:
                raise SystemExit(f"{rset['@id']}: field {field['name']!r} not in FIELDS.json")
            if field.get("dataType") != entry["croissant_type"]:
                field["dataType"] = entry["croissant_type"]
                retyped += 1
            desc = croissant_description(entry)
            if field.get("description") != desc:
                field["description"] = desc
                described += 1
            # keep key order readable: @type, @id, name, description, dataType, source
            for k in ("description", "dataType", "source"):
                if k in field:
                    field[k] = field.pop(k)
    if write:
        with open(path, "w") as fh:
            json.dump(cr, fh, indent=1, ensure_ascii=False)
            fh.write("\n")
    return retyped, described


def patch_readme(deposit, block, write):
    path = os.path.join(deposit, "README.md")
    with open(path) as fh:
        text = fh.read()
    if BEGIN not in text or END not in text:
        raise SystemExit(f"{path}: GENERATED markers not found; add {BEGIN} / {END} to section 2")
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    new = f"{head}{BEGIN}\n{block}\n{END}{tail}"
    if write and new != text:
        with open(path, "w") as fh:
            fh.write(new)
    return new != text


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--deposit", default="/workspace/deposit_v3")
    ap.add_argument("--data-records")
    ap.add_argument("--check", action="store_true", help="validate only, write nothing")
    a = ap.parse_args()

    d = load_dictionary(a.deposit)
    index = by_record_set(d)

    problems = verify_against_parquet(a.deposit, index)
    for p in problems:
        print("MISMATCH:", p, file=sys.stderr)
    if problems:
        return 1
    print(f"dictionary: {len(d['fields'])} fields over {len(d['record_sets'])} record sets; "
          "Parquet schema cross-check clean")

    write = not a.check
    md = render_fields_md(d, index)
    if write:
        with open(os.path.join(a.deposit, "FIELDS.md"), "w") as fh:
            fh.write(md)
    print(f"FIELDS.md: {len(md.splitlines())} lines{'' if write else ' (not written)'}")

    changed = patch_readme(a.deposit, render_readme_section(d), write)
    print(f"README.md section 2: {'updated' if changed else 'already current'}"
          f"{'' if write else ' (not written)'}")

    retyped, described = patch_croissant(a.deposit, index, write)
    print(f"croissant.json: {retyped} dataType corrections, {described} descriptions set"
          f"{'' if write else ' (not written)'}")

    if a.data_records:
        if write:
            with open(a.data_records, "w") as fh:
                fh.write(render_data_records(d))
        print(f"data records table -> {a.data_records}{'' if write else ' (not written)'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
